name: Deploy production

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: prod
      runner_label: prod
      compose_file: docker-compose.prod.yml
      image_tag: taskflow-api:prod
    secrets: inherit
