name: Deploy development

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: dev
      runner_label: dev
      compose_file: docker-compose.dev.yml
      image_tag: taskflow-api:dev
    secrets: inherit
